# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false
fortran: true

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

r:
 - release
 - devel

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

      r_binary_packages:
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - bindrcpp
        - RcppEigen
        - openssl
        - rlang
        - utf8
        - haven
        - data.table
        - dplyr
        - purrr
        - tidyr
        - readr
        - minqa
        - mvtnorm
        - nloptr
        - lme4
        - httpuv
        - markdown
        - readxl
        - openxlsx
        - pander

        # "These installs will be faster than source installs, but may not always be the most recent version"
        # https://docs.travis-ci.com/user/languages/r/#Additional-Dependency-Fields

    - os: osx
      osx_image: xcode9.3beta
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew install curl
        - brew link --force curl
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org


notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
